version: '3.9'

services:
  app:
    container_name: img_fastapi
    build: src/
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    env_file: '.env'
    environment:
      DB_HOST: db
    volumes:
      - ./src/app/:/code/
      - img_dir:${IMAGE_DIR_PATH}
    networks:
      - backend
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    container_name: img_fastapi_db 
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: '.env'
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    networks:
      - backend

  pgadmin:
    container_name: img_fastapi_pgadmin
    image: dpage/pgadmin4:latest
    env_file: '.env'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 15432:80
    networks:
      - backend
    depends_on:
      - db

  redis:
    container_name: img_fastapi_redis
    image: redis:latest
    networks:
      - backend

  celery_worker:
    container_name: img_fastapi_celery
    build: ./src
    command: celery -A common.celery_worker:celery worker --loglevel=info
    env_file: '.env'
    volumes:
      - ./src/app/:/code/
      - img_dir:${IMAGE_DIR_PATH}
    networks:
      - backend
    depends_on:
      - redis

  flower: 
    container_name: img_fastapi_flower
    build: ./src
    command: celery -A common.celery_worker:celery flower
    env_file: '.env'
    volumes:
      - ./src/app/:/code/
    ports:
      - 5555:5555
    networks:
      - backend
    depends_on:
      - celery_worker
      - redis

volumes:
  postgres_data:
  pgadmin:
  img_dir:

networks:
  backend:
    driver: bridge
